# Generated by Django 2.1.5 on 2019-08-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniusplazatest', '0002_auto_20190810_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='lasti',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
