# Generated by Django 2.1.5 on 2019-08-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geniusplazatest', '0003_recipe_lasti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='lasti',
        ),
    ]
